### PR TITLE
update version to 0.1.2

### PR DESCRIPTION
**Pull request by fs-eire**

### CODE REVIEW

**Comment by hariharans29** [comment]
Can we wait to upgrade to 0.1.2 until #47 is merged? That is required for the emotion_ferplus model perf improvement. I am working to address @fs-eire's comments?

**Comment by fs-eire** [comment]
Sure will hold this change till tomorrow.

**Comment by ykim** [comment]
Any chance that #72 and #73 could make it into this release?

**Comment by fs-eire** [comment]
@ykim No. not this time.

But 0.1.3 will come much sooner than 0.1.2 (which takes a month because of the holiday season)

**Pull request merged**
